version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  
  web:
    image: nsologub/yamdb:latest
    restart: always
    volumes:
      - ./static:/app/static/
      - ./media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/html/static/
      - ./media:media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
